travis: use opencv moved to brew core
This should fix CI where the opencv tap was not found anymore:

```
Tapped 630 formulae (667 files, 1.8MB)
Error: No available formula with the name "homebrew/science/opencv"
```